"""
the persisted schema: endpoints, the submissions addressed to them, and the
management credentials that administer the service
"""

from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    CheckConstraint,
    DateTime,
    ForeignKey,
    MetaData,
    String,
    TypeDecorator,
    UniqueConstraint,
)
from sqlalchemy.engine import Dialect
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from hymical_forms.apikeys import (
    DISPLAY_PREFIX_LENGTH,
    KEY_DIGEST_LENGTH,
    MANAGEMENT_KEY_ID_MAX_LENGTH,
    MANAGEMENT_KEY_NAME_MAX_LENGTH,
)
from hymical_forms.ingestion import (
    ENDPOINT_ID_MAX_LENGTH,
    IDEMPOTENCY_KEY_MAX_LENGTH,
    PAYLOAD_FINGERPRINT_LENGTH,
    SUBMISSION_ID_MAX_LENGTH,
)
from hymical_forms.ingestion import Submission as DomainSubmission
from hymical_forms.webhooks import (
    DELIVERY_ATTEMPT_ID_MAX_LENGTH,
    DELIVERY_ERROR_MAX_LENGTH,
    DELIVERY_STATE_MAX_LENGTH,
    WEBHOOK_DELIVERY_ID_MAX_LENGTH,
    WEBHOOK_SECRET_MAX_LENGTH,
    WEBHOOK_URL_MAX_LENGTH,
    DeliveryState,
)

ENDPOINT_NAME_MAX_LENGTH = 200
DELIVERY_OUTCOME_MAX_LENGTH = 32


def utcnow() -> datetime:
    """
    read the current time as a timezone-aware UTC timestamp
    :returns: the current instant in UTC
    """
    return datetime.now(UTC)


class UtcDateTime(TypeDecorator[datetime]):
    """
    a timestamp column that always stores and returns timezone-aware UTC values
    """

    # PostgreSQL round-trips ``TIMESTAMPTZ`` faithfully, but SQLite has no
    # timezone-aware storage and hands back a naive datetime. Normalising on the
    # way in and out keeps the two backends indistinguishable to the rest of the
    # code, so a value written as UTC is always read back as UTC.
    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        """
        convert a value on its way into the database
        :param value: the timestamp being stored, or None
        :param dialect: the active SQLAlchemy dialect
        :returns: the same instant expressed in UTC, or None
        :raises ValueError: if the timestamp carries no timezone
        """
        if value is None:
            return None
        if value.tzinfo is None:
            raise ValueError("naive datetimes cannot be stored, use a timezone-aware value")
        return value.astimezone(UTC)

    def process_result_value(self, value: datetime | None, dialect: Dialect) -> datetime | None:
        """
        convert a value on its way out of the database
        :param value: the stored timestamp, naive on backends without timezone support
        :param dialect: the active SQLAlchemy dialect
        :returns: a timezone-aware UTC timestamp, or None
        """
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)


class Base(DeclarativeBase):
    """
    declarative base for every persisted table
    """

    # Every constraint and index gets a predictable name rather than one the
    # database invents. Alembic needs that to reference them in a later
    # migration: an autogenerated foreign key name cannot be dropped portably.
    # Constraints that already carry an explicit name keep it.
    metadata = MetaData(
        naming_convention={
            "ix": "ix_%(table_name)s_%(column_0_N_name)s",
            "uq": "uq_%(table_name)s_%(column_0_N_name)s",
            "ck": "ck_%(table_name)s_%(constraint_name)s",
            "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
            "pk": "pk_%(table_name)s",
        }
    )


class Endpoint(Base):
    """
    a form ingestion destination that submissions may be addressed to
    """

    # The public endpoint ID is the primary key. It is already unique, immutable
    # in practice (changing it breaks every deployed HTML form pointing at it),
    # and constrained to a short safe character set, so a surrogate key would add
    # a join without buying anything.
    __tablename__ = "endpoints"

    __table_args__ = (
        # An endpoint either has a full webhook configuration or none of it. A URL
        # without a secret would mean sending unsigned payloads, which no receiver
        # could trust.
        CheckConstraint(
            "(webhook_url IS NULL) = (webhook_secret IS NULL)",
            name="webhook_configuration",
        ),
    )

    id: Mapped[str] = mapped_column(String(ENDPOINT_ID_MAX_LENGTH), primary_key=True)
    name: Mapped[str] = mapped_column(String(ENDPOINT_NAME_MAX_LENGTH))
    is_active: Mapped[bool] = mapped_column(default=True)
    created_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utcnow)

    # One destination per endpoint, held here rather than in a table of its own.
    # A separate table would only start paying for itself with several
    # destinations, which this build deliberately does not have.
    webhook_url: Mapped[str | None] = mapped_column(String(WEBHOOK_URL_MAX_LENGTH), default=None)
    webhook_secret: Mapped[str | None] = mapped_column(
        String(WEBHOOK_SECRET_MAX_LENGTH), default=None
    )


class Submission(Base):
    """
    a submission that was accepted for a persisted endpoint
    """

    __tablename__ = "submissions"

    __table_args__ = (
        # The database, not the application, is what makes an idempotency key
        # unique per endpoint. Two concurrent retries can both find nothing and
        # both try to insert, so the constraint is the only authoritative answer.
        #
        # Both PostgreSQL and SQLite treat NULLs in a unique constraint as
        # distinct from each other, so submissions sent without a key stay
        # unrestricted without needing a partial index on either backend.
        UniqueConstraint(
            "endpoint_id",
            "idempotency_key",
            name="uq_submissions_endpoint_idempotency_key",
        ),
        # A submission either carries a full idempotency identity or none of it.
        CheckConstraint(
            "(idempotency_key IS NULL) = (payload_fingerprint IS NULL)",
            name="idempotency_identity",
        ),
    )

    id: Mapped[str] = mapped_column(String(SUBMISSION_ID_MAX_LENGTH), primary_key=True)
    endpoint_id: Mapped[str] = mapped_column(
        String(ENDPOINT_ID_MAX_LENGTH),
        ForeignKey("endpoints.id"),
        index=True,
    )
    received_at: Mapped[datetime] = mapped_column(UtcDateTime)

    # Stored as ``{"field name": ["value", ...]}`` under SQLAlchemy's generic JSON
    # type, which is ``json`` on PostgreSQL rather than ``jsonb``. That is
    # deliberate: ``jsonb`` normalises object key order, which would silently
    # reorder a form's fields, and this payload is written once and read whole,
    # so ``jsonb`` indexing would buy nothing here. Every value is a list because
    # JSON has no tuple, so the domain's tuples widen here and narrow again in
    # :meth:`to_domain`.
    fields: Mapped[dict[str, list[str]]] = mapped_column(JSON)

    # Null for submissions sent without an ``Idempotency-Key``, which is the
    # common case. When present, the fingerprint is what tells a safe retry apart
    # from the same key being reused for different content.
    idempotency_key: Mapped[str | None] = mapped_column(
        String(IDEMPOTENCY_KEY_MAX_LENGTH), default=None
    )
    payload_fingerprint: Mapped[str | None] = mapped_column(
        String(PAYLOAD_FINGERPRINT_LENGTH), default=None
    )

    @classmethod
    def from_domain(
        cls,
        submission: DomainSubmission,
        *,
        idempotency_key: str | None = None,
        payload_fingerprint: str | None = None,
    ) -> Submission:
        """
        build a persistable row from a validated domain submission
        :param submission: the normalized submission to store
        :param idempotency_key: the client's retry key, or None if it sent none
        :param payload_fingerprint: digest of the submitted content, set only alongside a key
        :returns: an unsaved row mirroring the submission
        """
        return cls(
            id=submission.id,
            endpoint_id=submission.endpoint_id,
            received_at=submission.received_at,
            fields={name: list(values) for name, values in submission.fields.items()},
            idempotency_key=idempotency_key,
            payload_fingerprint=payload_fingerprint,
        )

    def to_domain(self) -> DomainSubmission:
        """
        rebuild the domain submission this row was stored from
        :returns: the submission with its repeated field values restored as tuples
        """
        return DomainSubmission(
            id=self.id,
            endpoint_id=self.endpoint_id,
            received_at=self.received_at,
            fields={name: tuple(values) for name, values in self.fields.items()},
        )


class WebhookDelivery(Base):
    """
    the durable obligation to deliver one submission to one destination
    """

    # This is the outbox. It is written in the same transaction as the submission
    # it belongs to, so a submission can never be acknowledged while the promise
    # to deliver it quietly goes missing.
    __tablename__ = "webhook_deliveries"

    __table_args__ = (
        # One logical delivery per submission. An idempotent replay resolves to an
        # existing submission, so this constraint is what makes "a replay never
        # queues a second delivery" a property of the database rather than of the
        # code path that happens to run.
        UniqueConstraint("submission_id", name="uq_webhook_deliveries_submission"),
        # A delivery is finished exactly when it says it is finished.
        CheckConstraint(
            "(state IN ('delivered', 'failed')) = (completed_at IS NOT NULL)",
            name="completion",
        ),
    )

    id: Mapped[str] = mapped_column(String(WEBHOOK_DELIVERY_ID_MAX_LENGTH), primary_key=True)
    submission_id: Mapped[str] = mapped_column(
        String(SUBMISSION_ID_MAX_LENGTH), ForeignKey("submissions.id")
    )

    # The destination and secret are snapshotted, not read through to the
    # endpoint. A delivery represents what was owed when the submission was
    # accepted, so changing an endpoint's webhook later must not silently
    # redirect work that is already queued, nor leave a queued payload signed
    # with a secret its receiver never had.
    destination_url: Mapped[str] = mapped_column(String(WEBHOOK_URL_MAX_LENGTH))
    signing_secret: Mapped[str] = mapped_column(String(WEBHOOK_SECRET_MAX_LENGTH))

    state: Mapped[str] = mapped_column(
        String(DELIVERY_STATE_MAX_LENGTH), default=DeliveryState.PENDING
    )
    attempts: Mapped[int] = mapped_column(default=0)

    # When this delivery next becomes due. Indexed with the state because that
    # pair is exactly what a worker scans for on every poll.
    next_attempt_at: Mapped[datetime] = mapped_column(UtcDateTime, index=True)

    # Set while a worker holds the job. A lease that has run out makes the job
    # claimable again, which is what stops a worker that died mid-delivery from
    # leaving a permanent ``processing`` tombstone.
    claim_expires_at: Mapped[datetime | None] = mapped_column(UtcDateTime, default=None)

    created_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utcnow)
    completed_at: Mapped[datetime | None] = mapped_column(UtcDateTime, default=None)


class DeliveryAttempt(Base):
    """
    a record of one outbound request actually made for a delivery
    """

    # The audit trail. One row per request that genuinely went out, so a delivery
    # that was retried four times has four rows and none of them is overwritten.
    # A job that is merely inspected and found not due produces nothing here.
    __tablename__ = "delivery_attempts"

    id: Mapped[str] = mapped_column(String(DELIVERY_ATTEMPT_ID_MAX_LENGTH), primary_key=True)
    delivery_id: Mapped[str] = mapped_column(
        String(WEBHOOK_DELIVERY_ID_MAX_LENGTH),
        ForeignKey("webhook_deliveries.id"),
        index=True,
    )
    submission_id: Mapped[str] = mapped_column(
        String(SUBMISSION_ID_MAX_LENGTH),
        ForeignKey("submissions.id"),
        index=True,
    )
    attempt_number: Mapped[int] = mapped_column()

    # The URL as it was used, not as it is configured now, so the record still
    # explains itself after the endpoint's destination changes.
    destination_url: Mapped[str] = mapped_column(String(WEBHOOK_URL_MAX_LENGTH))
    attempted_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utcnow)

    # Stored as plain text rather than a database enum, because a database enum
    # would need a migration to gain a value and there is no migration tool yet.
    outcome: Mapped[str] = mapped_column(String(DELIVERY_OUTCOME_MAX_LENGTH))
    response_status: Mapped[int | None] = mapped_column(default=None)

    # Response bodies are deliberately not stored. They are unbounded, written by
    # somebody else's server, and nothing in this build reads them back.
    error: Mapped[str | None] = mapped_column(String(DELIVERY_ERROR_MAX_LENGTH), default=None)


class ManagementApiKey(Base):
    """
    a credential that authenticates management requests against this service
    """

    # These keys administer the whole service. There is no account, tenant or
    # role model to attach them to, and inventing owner columns for one would be
    # guessing at a design nothing has asked for yet. Endpoints deliberately do
    # not record which key created them for the same reason.
    __tablename__ = "management_api_keys"

    __table_args__ = (
        # Authentication resolves a candidate by digest, so this constraint is
        # both the uniqueness guarantee and the index that lookup rides on.
        UniqueConstraint("key_digest", name="uq_management_api_keys_key_digest"),
    )

    id: Mapped[str] = mapped_column(String(MANAGEMENT_KEY_ID_MAX_LENGTH), primary_key=True)
    name: Mapped[str] = mapped_column(String(MANAGEMENT_KEY_NAME_MAX_LENGTH))

    # The prefix and the first few characters of the secret, so an operator can
    # tell two credentials apart in a listing. Everything after it is missing,
    # which is what makes the fragment safe to display and to log.
    display_prefix: Mapped[str] = mapped_column(String(DISPLAY_PREFIX_LENGTH))

    # The only representation of the credential this service keeps. The key
    # itself is never written anywhere: whoever creates one either saves it at
    # that moment or makes another.
    key_digest: Mapped[str] = mapped_column(String(KEY_DIGEST_LENGTH))

    created_at: Mapped[datetime] = mapped_column(UtcDateTime, default=utcnow)

    # Revocation sets a timestamp rather than deleting the row, so the identity
    # and the history of a withdrawn credential survive being withdrawn.
    revoked_at: Mapped[datetime | None] = mapped_column(UtcDateTime, default=None)

    # Best-effort telemetry, written after a request has already authenticated.
    # Nothing decides anything on it, which is what lets a failure to update it
    # be ignored rather than turning a valid key into a rejected one.
    last_used_at: Mapped[datetime | None] = mapped_column(UtcDateTime, default=None)

    @property
    def is_active(self) -> bool:
        """
        report whether this key still authenticates
        :returns: True if the key has not been revoked
        """
        return self.revoked_at is None
